version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: istory
      MYSQL_USER: dangtong
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    # 밖에 선언한 볼륨을 안에 이제 쓰겠다!!
    volumes: 
      - mysql-data:/var/lib/mysql

# 밖에 선언한 볼륨 정의
volumes: 
  mysql-data:
    external: true
    name: mysql-data